name: belang
description: Belang is a privacy-first, AI-enhanced language exchange app designed to protect users from unwanted flirtation, harassment, and grooming through layered, adaptive moderation.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_chat_ui: ^2.6.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  isar: ^3.1.0+1
  logger: ^2.6.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
